# Dockerfile.server

FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY server/ ./server
COPY shared/ ./shared

# Устанавливаем tsx как зависимость
RUN npm install tsx

CMD ["npx", "tsx", "server/index.ts"]
