FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
COPY tsconfig*.json ./
COPY server/ ./server
COPY shared/ ./shared

# Очищаем NODE_ENV на время установки — иначе dev-зависимости игнорируются
RUN --mount=type=cache,target=/root/.npm \
    npm config set production false && npm ci

CMD ["node", "--loader", "tsx", "server/index.ts"]
