services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    volumes:
      - ./certs:/etc/ssl/certs:ro
    environment:
      - CERTS_PATH=/etc/ssl/certs
      - ADMIN_PASSWORD=4ik18e
    ports:
      - "3000:3000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./certs:/etc/ssl/certs:ro
      - ./certbot-webroot:/var/www/certbot:ro
