# Dockerfile.server
FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
COPY tsconfig*.json ./
COPY server/ ./server
COPY shared/ ./shared

RUN npm ci

# Устанавливаем tsx как зависимость
RUN npm install tsx

# Используем npx tsx для запуска без компиляции
CMD ["npx", "tsx", "server/index.ts"]
