export enum FieldType {
  Ques3 = '3chance',
  Ques = 'chance',
  Pip = 'pip',
  Start = 'start',
  Taxi = 'taxi',
  Jail = 'jail',
  Birga = 'stock-exchange',
  Firm = 'firm'
}

export enum Country {
  SWI = 'Switzerland',
  HOL = 'Holland',
  ITA = 'Italy',
  HUN = 'Hungary',
  GER = 'Germany',
  FRA = 'France',
  BLK = 'Balkan',
  JAP = 'Japan',
  ENG = 'England',
  USA = 'USA',
  URS = 'USSR',
}

export enum Industry {
  Port = 'Port',
  Spy = 'Spy',
  Healthcare = 'Healthcare',
  Tourism = 'Tourism',
  Radio = 'Radio',
  Food = 'Food',
  Media = 'Media',
  Automotive = 'Automotive',
  Electro = 'Electro',
  Oil = 'Oil',
  Studio = 'Studio',
  Avia = 'Avia',
  Newspaper = 'Newspaper',
}

export type FieldDefinition = {
  index: number;
  type: FieldType;
  name?: string;
  cost?: number;
  baseIncome?: number;
  investmentLevels?: number[]; // Уровни дохода при улучшениях
  country?: Country;
  industry?: Industry;
};

export const fieldDefinitions: FieldDefinition[] = [
  {
    index: 0,
    type: FieldType.Ques3,
  },
  {
    index: 1,
    type: FieldType.Firm,
    name: 'ESSO',
    cost: 20,
    baseIncome: 2,
    country: Country.USA,
    industry: Industry.Oil,
  },
  {
    index: 2,
    type: FieldType.Firm,
    name: 'British Petrolium',
    cost: 25,
    baseIncome: 2.5,
    country: Country.ENG,
    industry: Industry.Oil,
  },
  {
    index: 3,
    type: FieldType.Ques,
  },
  {
    index: 4,
    type: FieldType.Firm,
    name: 'Shell',
    cost: 30,
    baseIncome: 3,
    country: Country.HOL,
    industry: Industry.Oil,
  },
  {
    index: 5,
    type: FieldType.Firm,
    name: 'Yokogama',
    cost: 20,
    baseIncome: 5,
    country: Country.JAP,
    industry: Industry.Port,
  },
  {
    index: 6,
    type: FieldType.Firm,
    name: 'Борба',
    cost: 25,
    baseIncome: 2.5,
    country: Country.BLK,
    industry: Industry.Radio,
  },
  {
    index: 7,
    type: FieldType.Firm,
    name: 'BBC',
    cost: 30,
    baseIncome: 3,
    country: Country.ENG,
    industry: Industry.Radio,
  },
  {
    index: 8,
    type: FieldType.Pip,
  },
  {
    index: 9,
    type: FieldType.Firm,
    name: 'Маяк',
    cost: 35,
    baseIncome: 3.5,
    country: Country.URS,
    industry: Industry.Radio,
  },
  {
    index: 10,
    type: FieldType.Taxi,
  },
  {
    index: 11,
    type: FieldType.Firm,
    name: 'Bulgarconserv',
    cost: 8,
    baseIncome: 0.8,
    country: Country.BLK,
    industry: Industry.Food,
  },
  {
    index: 12,
    type: FieldType.Firm,
    name: 'Coca-Cola',
    cost: 12,
    baseIncome: 1.2,
    country: Country.USA,
    industry: Industry.Food,
  },
  {
    index: 13,
    type: FieldType.Ques,
  },
  {
    index: 14,
    type: FieldType.Firm,
    name: 'Globus',
    cost: 16,
    baseIncome: 1.6,
    country: Country.HUN,
    industry: Industry.Food,
  },
  {
    index: 15,
    type: FieldType.Firm,
    name: 'Rostoc',
    cost: 20,
    baseIncome: 5,
    country: Country.GER,
    industry: Industry.Port,
  },
  {
    index: 16,
    type: FieldType.Firm,
    name: 'BEA',
    cost: 50,
    baseIncome: 5,
    country: Country.ENG,
    industry: Industry.Avia,
  },
  {
    index: 17,
    type: FieldType.Firm,
    name: 'Lufthanza',
    cost: 60,
    baseIncome: 6,
    country: Country.GER,
    industry: Industry.Avia,
  },
  {
    index: 18,
    type: FieldType.Pip,
  },
  {
    index: 19,
    type: FieldType.Firm,
    name: 'Air France',
    cost: 70,
    baseIncome: 7,
    country: Country.FRA,
    industry: Industry.Avia,
  },
  {
    index: 20,
    type: FieldType.Birga,
  },
  {
    index: 21,
    type: FieldType.Firm,
    name: 'Omega',
    cost: 6,
    baseIncome: 0.6,
    country: Country.SWI,
    industry: Industry.Electro,
  },
  {
    index: 22,
    type: FieldType.Firm,
    name: 'Grundic',
    cost: 8,
    baseIncome: 0.8,
    country: Country.GER,
    industry: Industry.Electro,
  },
  {
    index: 23,
    type: FieldType.Ques,
  },
  {
    index: 24,
    type: FieldType.Firm,
    name: 'Bell',
    cost: 10,
    baseIncome: 1,
    country: Country.USA,
    industry: Industry.Electro,
  },
  {
    index: 25,
    type: FieldType.Firm,
    name: 'Roterdam',
    cost: 20,
    baseIncome: 5,
    country: Country.HOL,
    industry: Industry.Port,
  },
  {
    index: 26,
    type: FieldType.Firm,
    name: 'NG',
    cost: 30,
    baseIncome: 3,
    country: Country.FRA,
    industry: Industry.Spy,
  },
  {
    index: 27,
    type: FieldType.Firm,
    name: 'IS',
    cost: 35,
    baseIncome: 3.5,
    country: Country.ENG,
    industry: Industry.Spy,
  },
  {
    index: 28,
    type: FieldType.Pip,
  },
  {
    index: 29,
    type: FieldType.Firm,
    name: 'CIA',
    cost: 40,
    baseIncome: 4,
    country: Country.USA,
    industry: Industry.Spy,
  },
  {
    index: 30,
    type: FieldType.Jail,
  },
  {
    index: 31,
    type: FieldType.Firm,
    name: 'Союзмультфильм',
    cost: 15,
    baseIncome: 1.5,
    country: Country.URS,
    industry: Industry.Studio,
  },
  {
    index: 32,
    type: FieldType.Firm,
    name: 'Defa',
    cost: 10,
    baseIncome: 1,
    country: Country.GER,
    industry: Industry.Studio,
  },
  {
    index: 33,
    type: FieldType.Ques,
  },
  {
    index: 34,
    type: FieldType.Firm,
    name: 'XX-th centure fox',
    cost: 20,
    baseIncome: 1.5,
    country: Country.USA,
    industry: Industry.Studio,
  },
  {
    index: 35,
    type: FieldType.Firm,
    name: 'Genoa',
    cost: 20,
    baseIncome: 5,
    country: Country.ITA,
    industry: Industry.Port,
  },
  {
    index: 36,
    type: FieldType.Firm,
    name: 'Tanug',
    cost: 15,
    baseIncome: 1.5,
    country: Country.BLK,
    industry: Industry.Media,
  },
  {
    index: 37,
    type: FieldType.Firm,
    name: 'Reuter',
    cost: 20,
    baseIncome: 2,
    country: Country.ENG,
    industry: Industry.Media,
  },
  {
    index: 38,
    type: FieldType.Pip,
  },
  {
    index: 39,
    type: FieldType.Firm,
    name: 'France Press',
    cost: 25,
    baseIncome: 2.5,
    country: Country.FRA,
    industry: Industry.Media,
  },
  {
    index: 40,
    type: FieldType.Firm,
    name: 'Toyota',
    cost: 15,
    baseIncome: 5,
    country: Country.JAP,
    industry: Industry.Automotive,
  },
  {
    index: 41,
    type: FieldType.Firm,
    name: 'Weimar',
    cost: 10,
    baseIncome: 10,
    country: Country.GER,
    industry: Industry.Tourism,
  },
  {
    index: 42,
    type: FieldType.Firm,
    name: 'Zarichev Zaitung',
    cost: 20,
    baseIncome: 3,
    country: Country.SWI,
    industry: Industry.Newspaper,
  },
  {
    index: 43,
    type: FieldType.Firm,
    name: 'Колыма',
    cost: 20,
    baseIncome: 2,
    country: Country.URS,
    industry: Industry.Healthcare,
  },
  {
    index: 44,
    type: FieldType.Start,
  },
  {
    index: 45,
    type: FieldType.Firm,
    name: 'Icarus',
    cost: 20,
    baseIncome: 10,
    country: Country.HUN,
    industry: Industry.Automotive,
  },
  {
    index: 46,
    type: FieldType.Firm,
    name: 'Volksvagen',
    cost: 15,
    baseIncome: 5,
    country: Country.GER,
    industry: Industry.Automotive,
  },
  {
    index: 47,
    type: FieldType.Firm,
    name: 'Nizza',
    cost: 60,
    baseIncome: 6,
    country: Country.FRA,
    industry: Industry.Healthcare,
  },
  {
    index: 48,
    type: FieldType.Firm,
    name: 'Fiat',
    cost: 20,
    baseIncome: 5,
    country: Country.ITA,
    industry: Industry.Automotive,
  },
  {
    index: 49,
    type: FieldType.Firm,
    name: 'Мурзилка',
    cost: 15,
    baseIncome: 5,
    country: Country.URS,
    industry: Industry.Newspaper,
  },
  {
    index: 50,
    type: FieldType.Firm,
    name: 'Lozanna',
    cost: 80,
    baseIncome: 8,
    country: Country.SWI,
    industry: Industry.Healthcare,
  },
  {
    index: 51,
    type: FieldType.Firm,
    name: 'Fudziama',
    cost: 10,
    baseIncome: 10,
    country: Country.JAP,
    industry: Industry.Tourism,
  },
  {
    index: 52,
    type: FieldType.Firm,
    name: 'Запорожец',
    cost: 15,
    baseIncome: 3,
    country: Country.URS,
    industry: Industry.Automotive,
  },
  {
    index: 53,
    type: FieldType.Firm,
    name: 'Unita',
    cost: 20,
    baseIncome: 3,
    country: Country.ITA,
    industry: Industry.Newspaper,
  },
  {
    index: 54,
    type: FieldType.Firm,
    name: 'Playboy',
    cost: 40,
    baseIncome: 20,
    country: Country.USA,
    industry: Industry.Newspaper,
  },
  {
    index: 55,
    type: FieldType.Firm,
    name: 'Renult',
    cost: 15,
    baseIncome: 3,
    country: Country.FRA,
    industry: Industry.Automotive,
  },
  {
    index: 56,
    type: FieldType.Firm,
    name: 'Venesia',
    cost: 40,
    baseIncome: 4,
    country: Country.ITA,
    industry: Industry.Tourism,
  },
];
