export enum FieldType {
  Ques3 = '3chance',
  Ques = 'chance',
  Pip = 'pip',
  Start = 'start',
  Taxi = 'taxi',
  Jail = 'jail',
  Birga = 'stock exchange',
  Firm = 'property'
}

export interface FieldDefinition {
  index: number;
  type: FieldType;
  name?: string;
  cost?: number;
  baseIncome?: number;
  investmentLevels?: number[]; // Уровни дохода при улучшениях
}

export const fieldDefinitions: FieldDefinition[] = [
  {
    index: 0,
    type: FieldType.Ques3,
  },
  {
    index: 1,
    type: FieldType.Firm,
    name: 'ESSO',
    cost: 20,
    baseIncome: 2,
  },
  {
    index: 2,
    type: FieldType.Firm,
    name: 'British Petrolium',
    cost: 25,
    baseIncome: 2.5,
  },
  {
    index: 3,
    type: FieldType.Ques,
  },
  {
    index: 4,
    type: FieldType.Firm,
    name: 'Shell',
    cost: 30,
    baseIncome: 3,
  },
  {
    index: 5,
    type: FieldType.Firm,
    name: 'Yokogama',
    cost: 20,
    baseIncome: 5,
  },
  {
    index: 6,
    type: FieldType.Firm,
    name: 'Борба',
    cost: 25,
    baseIncome: 2.5,
  },
  {
    index: 7,
    type: FieldType.Firm,
    name: 'BBC',
    cost: 30,
    baseIncome: 3,
  },
  {
    index: 8,
    type: FieldType.Pip,
  },
  {
    index: 9,
    type: FieldType.Firm,
    name: 'Маяк',
    cost: 35,
    baseIncome: 3.5,
  },
  {
    index: 10,
    type: FieldType.Taxi,
  },
  {
    index: 11,
    type: FieldType.Firm,
    name: 'Bulgarconserv',
    cost: 8,
    baseIncome: 0.8,
  },
  {
    index: 12,
    type: FieldType.Firm,
    name: 'Coca-Cola',
    cost: 12,
    baseIncome: 1.2,
  },
  {
    index: 13,
    type: FieldType.Ques,
  },
  {
    index: 14,
    type: FieldType.Firm,
    name: 'Globus',
    cost: 16,
    baseIncome: 1.6,
  },
  {
    index: 15,
    type: FieldType.Firm,
    name: 'Rostoc',
    cost: 20,
    baseIncome: 5,
  },
  {
    index: 16,
    type: FieldType.Firm,
    name: 'BEA',
    cost: 50,
    baseIncome: 5,
  },
  {
    index: 17,
    type: FieldType.Firm,
    name: 'Lufthanza',
    cost: 60,
    baseIncome: 6,
  },
  {
    index: 18,
    type: FieldType.Pip,
  },
  {
    index: 19,
    type: FieldType.Firm,
    name: 'Air France',
    cost: 70,
    baseIncome: 7,
  },
  {
    index: 20,
    type: FieldType.Birga,
  },
  {
    index: 21,
    type: FieldType.Firm,
    name: 'Omega',
    cost: 6,
    baseIncome: 0.6,
  },
  {
    index: 22,
    type: FieldType.Firm,
    name: 'Grundic',
    cost: 8,
    baseIncome: 0.8,
  },
  {
    index: 23,
    type: FieldType.Ques,
  },
  {
    index: 24,
    type: FieldType.Firm,
    name: 'Bell',
    cost: 10,
    baseIncome: 1,
  },
  {
    index: 25,
    type: FieldType.Firm,
    name: 'Roterdam',
    cost: 20,
    baseIncome: 5,
  },
  {
    index: 26,
    type: FieldType.Firm,
    name: 'NG',
    cost: 30,
    baseIncome: 3,
  },
  {
    index: 27,
    type: FieldType.Firm,
    name: 'IS',
    cost: 35,
    baseIncome: 3.5,
  },
  {
    index: 28,
    type: FieldType.Pip,
  },
  {
    index: 29,
    type: FieldType.Firm,
    name: 'CIA',
    cost: 40,
    baseIncome: 4,
  },
  {
    index: 30,
    type: FieldType.Jail,
  },
  {
    index: 31,
    type: FieldType.Firm,
    name: 'Союзмультфильм',
    cost: 15,
    baseIncome: 1.5,
  },
  {
    index: 32,
    type: FieldType.Firm,
    name: 'Defa',
    cost: 10,
    baseIncome: 1,
  },
  {
    index: 33,
    type: FieldType.Ques,
  },
  {
    index: 34,
    type: FieldType.Firm,
    name: 'XX-th centure fox',
    cost: 20,
    baseIncome: 1.5,
  },
  {
    index: 35,
    type: FieldType.Firm,
    name: 'Genoa',
    cost: 20,
    baseIncome: 5,
  },
  {
    index: 36,
    type: FieldType.Firm,
    name: 'Tanug',
    cost: 15,
    baseIncome: 1.5,
  },
  {
    index: 37,
    type: FieldType.Firm,
    name: 'Reuter',
    cost: 20,
    baseIncome: 2,
  },
  {
    index: 38,
    type: FieldType.Pip,
  },
  {
    index: 39,
    type: FieldType.Firm,
    name: 'France Press',
    cost: 25,
    baseIncome: 2.5,
  },
  {
    index: 40,
    type: FieldType.Firm,
    name: 'Toyota',
    cost: 15,
    baseIncome: 5,
  },
  {
    index: 41,
    type: FieldType.Firm,
    name: 'Weimar',
    cost: 10,
    baseIncome: 10,
  },
  {
    index: 42,
    type: FieldType.Firm,
    name: 'Zarichev Zaitung',
    cost: 20,
    baseIncome: 3,
  },
  {
    index: 43,
    type: FieldType.Firm,
    name: 'Колыма',
    cost: 20,
    baseIncome: 2,
  },
  {
    index: 44,
    type: FieldType.Start,
  },
  {
    index: 45,
    type: FieldType.Firm,
    name: 'Icarus',
    cost: 20,
    baseIncome: 10,
  },
  {
    index: 46,
    type: FieldType.Firm,
    name: 'Volksvagen',
    cost: 15,
    baseIncome: 5,
  },
  {
    index: 47,
    type: FieldType.Firm,
    name: 'Nizza',
    cost: 60,
    baseIncome: 6,
  },
  {
    index: 48,
    type: FieldType.Firm,
    name: 'Fiat',
    cost: 20,
    baseIncome: 5,
  },
  {
    index: 49,
    type: FieldType.Firm,
    name: 'Мурзилка',
    cost: 15,
    baseIncome: 5,
  },
  {
    index: 50,
    type: FieldType.Firm,
    name: 'Lozanna',
    cost: 80,
    baseIncome: 8,
  },
  {
    index: 51,
    type: FieldType.Firm,
    name: 'Fudziama',
    cost: 10,
    baseIncome: 10,
  },
  {
    index: 52,
    type: FieldType.Firm,
    name: 'Запорожец',
    cost: 15,
    baseIncome: 3,
  },
  {
    index: 53,
    type: FieldType.Firm,
    name: 'Unita',
    cost: 20,
    baseIncome: 3,
  },
  {
    index: 54,
    type: FieldType.Firm,
    name: 'Playboy',
    cost: 40,
    baseIncome: 20,
  },
  {
    index: 55,
    type: FieldType.Firm,
    name: 'Renult',
    cost: 15,
    baseIncome: 3,
  },
  {
    index: 56,
    type: FieldType.Firm,
    name: 'Venesia',
    cost: 40,
    baseIncome: 4,
  },
];
